### PR TITLE
Update metafile to see if class and test is picked up.

### PR DESCRIPTION
**Pull request by buggyb12**

### CODE REVIEW

**Comment by buggyb12** [comment]
test this please

**Comment by buggyb12** [comment]
test this please

**Comment by Dhanielk** [comment]
test this please

**Comment by Dhanielk** [comment]
test this please

**Comment by Dhanielk** [comment]
test this please

**Comment by Dhanielk** [comment]
test this please

**Comment by Dhanielk** [comment]
Test this please

**Comment by Dhanielk** [comment]
test this please

**Comment by Dhanielk** [comment]
test this please

**Comment by Dhanielk** [comment]
test this please

**Comment by Dhanielk** [comment]
test this please

**Comment by Dhanielk** [comment]
test this please

**Comment by Dhanielk** [comment]
test this please

**Comment by Dhanielk** [comment]
test this please...

**Comment by Dhanielk** [comment]
test this please

**Comment by buggyb12** [comment]
test this please

**Comment by buggyb12** [comment]
test this please

**Comment by buggyb12** [comment]
test this please

**Pull request merged**
